config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/callback', to: 'sessions#google_create'
  delete '/logout', to: 'sessions#destroy'
  post '/favorite/:id', to: 'favorites#create', as: 'create_favorite'
  delete '/favorite/:id', to: 'favorites#destroy', as: 'destroy_favorite'
  get 'tips_index', to: 'tips#tips_index'
  get 'tips/how_to_street_view'

  resources :users do
    resources :tips
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tip.rb
class Tip < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  mount_uploader :img, ImgUploaderUploader

  validates :tips_type, presence: true
  validates :country, presence: true
  validates :tips_content, length: { maximum: 200 }
  validate :street_view_url_is_invalid_if_different_to_googlemap

  def street_view_url_is_invalid_if_different_to_googlemap
    errors.add(:street_view, "が無効です。") if street_view.present? && street_view.slice(0..32) != "https://www.google.com/maps/embed"
  end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_user_id, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  before_action :login_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :admin_or_correct_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_countries, only: [:index, :tips_index, :new, :create, :edit, :update]
  before_action :set_categories, only: [:index, :tips_index, :new, :create, :edit, :update]

  def show
    redirect_to tips_index_url unless @tip = Tip.find_by(id: params[:id])
  end

  # 特定のユーザーのTips一覧
  def index
    if params[:tips_condition]
      tips = Tip.all
      tips = tips.where(country: params[:tips_condition][:country]) if params[:tips_condition].present? && params[:tips_condition][:country].present?
      tips = tips.where('tips_type LIKE ?', "%#{params[:tips_condition][:tips_type]}%") if params[:tips_condition].present? && params[:tips_condition][:tips_type].present?
      tips = tips.where('tips_content LIKE ?', "%#{params[:tips_condition][:tips_content]}%") if params[:tips_condition].present? && params[:tips_condition][:tips_content].present?
       # favoritesに自分がお気に入りに登録したTipsのidを格納、pluckで配列型に変換、keyは:tip_id
      if params[:tips_condition][:user_favorite] == "1"
        favorites = Favorite.where(user_id: current_user.id).pluck(:tip_id)
        tips = tips.where(id: favorites)
      end
      @tips = tips.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
    else
      @tips = @user.tips.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
    end
    if @tips.blank?
      flash.now[:success] = "Tipsが見つかりませんでした。"
    else
      flash.now[:success] = "#{@tips.count}件のTipsが見つかりました。"
    end
  end

  # 全Tips一覧
  def tips_index
    if params[:tips_condition].present?
      tips = Tip.all
      tips = tips.where(country: params[:tips_condition][:country]) if params[:tips_condition][:country].present?
      tips = tips.where('tips_type LIKE ?', "%#{params[:tips_condition][:tips_type]}%") if params[:tips_condition][:tips_type].present?
      tips = tips.where('tips_content LIKE ?', "%#{params[:tips_condition][:tips_content]}%") if params[:tips_condition][:tips_content].present?
      # favoritesに自分がお気に入りに登録したTipsのidを格納、pluckで配列型に変換、keyは:tip_id
      if params[:tips_condition][:user_favorite] == "1"
        favorites = Favorite.where(user_id: current_user.id).pluck(:tip_id)
        tips = tips.where(id: favorites)
      end
      @tips = tips.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
    else
      @tips = Tip.all.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
    end
    if @tips.blank?
      flash.now[:success] = "Tipsが見つかりませんでした。"
    else
      flash.now[:success] = "#{@tips.count}件のTipsが見つかりました。"
    end
  end

  def new
    @tip = @user.tips.new
  end

  def create
    @tip = @user.tips.new
    tp = tip_params
    tp[:street_view] = URI.extract(tp[:street_view])[0]
    if tip_params[:street_view].present? && tp[:street_view].nil?
      tp[:street_view] = tip_params[:street_view]
    end
    if @tip.update_attributes(tp)
      redirect_to user_tip_url(@user, @tip)
    else
      render :new
    end
  end

  def edit
    @tip = Tip.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @tip = Tip.find(params[:id])
    etp = edit_tip_params
    etp[:street_view] = URI.extract(etp[:street_view], ["https"])[0]
    if edit_tip_params[:street_view].present? && etp[:street_view].nil?
      etp[:street_view] = edit_tip_params[:street_view]
    end
    if etp[:remove_img] == "1"
      @tip.remove_img!
      @tip.save
    end
    if @tip.update_attributes(etp)
      flash[:success] = "Tipsを編集しました。"
      redirect_to user_tip_path(@user, @tip)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @tip = Tip.find(params[:id])
    @tip.destroy
    flash[:success] = "Tipsを削除しました。"
    redirect_to @user
  end

  def how_to_street_view
  end

  private
    def tip_params
      params.require(:user).permit(:user_favorite, tips: [:tips_type, :country, :tips_content, :street_view, :img, :user_favorite])[:tips]
    end

    def edit_tip_params
      params.require(:tip).permit(:tips_type, :country, :tips_content, :street_view, :img, :remove_img)
    end

    def set_user_id
      redirect_to root_url unless @user = User.find_by(id: params[:user_id])
    end
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/tips/_favorite.html.erb
<div id="favorite_<%= tip.id %>" >
  <% if !Favorite.exists?(user: current_user, tip_id: tip.id) %>
    <%= link_to "お気に入りに登録　#{tip.favorites.count}", create_favorite_path(tip), method: :post, remote: true, class: "btn btn-default btn-favorite" %>
  <% else %>
    <%= link_to "お気に入りから外す　#{tip.favorites.count}", destroy_favorite_path(tip), method: :delete, remote: true, class: "btn btn-default btn-favorite" %>
  <% end %>
</div>

app/views/tips/_how_to_street_view.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">【ストリートビューの貼り付け方法】</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <p class="street_view">① 左上の3つの点をクリックし、「画像を共有または埋め込む」をクリック</p>
          <%= image_tag "street_view_1 (2).jpg", class: "street_view_jpg" %>
          <p class="street_view">②「地図を埋め込む」を選択し、「HTMLをコピー」</p>
          <%= image_tag "street_view_2 (2).jpg", class: "street_view_jpg" %>
          <p class="street_view">③ストリートビューURLへ貼り付けて投稿してください。</p>
          <%= image_tag "street_view_3 (2).jpg", class: "street_view_jpg" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tips/edit.html.erb
<% provide(:title, "Tips編集") %>

<h1>Tipsの編集</h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_with(model: @tip, url: user_tip_path, local: true) do |f| %>
      <%= render 'shared/tip_error_messages' %>
      <%= f.label :country, class: "label-tips" %>
      <%= f.select :country, @countries, { selected: @tip.country }, class: "form-control" %>

      <%= f.label :tips_type, class: "label-tips" %>
      <%= f.select :tips_type, @categories, { selected: @tip.tips_type }, class: "form-control" %>

      <%= f.label :tips_content, class: "label-tips" %>
      <%= f.text_area :tips_content, class: "form-control" %>

      <%= f.label :street_view, class: "label-tips" %>
        <%= link_to "URLの貼り付け方はこちら", tips_how_to_street_view_path, remote: true, class: "how-to" %>
      <%= f.text_field :street_view, class: "form-control" %>

      <%= f.label :img, class: "label-tips" %>
      <%= f.file_field :img, class: 'form-control' %>
      <%= f.hidden_field :img_cache %>

      <% if @tip.img.present? %>
        <%= f.label :remove_img, class: "checkbox inline checkbox-img", for: "remove_img" do %>
          <%= f.check_box :remove_img, id: "remove_img" %>
          <span>アップロードされている画像を削除する</span>
        <% end %>
        <p>
          <%= image_tag @tip.img.url, class: 'rounded-circle mr15', width: '100%' %>
        </p>
      
      <% end %>
      

      <%= f.submit "編集", class: "btn btn-block btn-primary btn-tips-form" %>
    <% end %>
  </div>
</div>


<div id="how-to-street-view" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/tips/how_to_street_view.js.erb
$("#how-to-street-view").html("<%= escape_javascript(render 'how_to_street_view') %>");
$("#how-to-street-view").modal("show");

app/views/tips/index.html.erb
<% provide(:title, @user.name + "のTips一覧") %>

<h1><%= @user.name %>のTips一覧</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="index-form">
      <%= form_with(scope: :tips_condition, url: user_tips_path, method: :get, local: true) do |f| %>
        <%= f.label :country, "国名", class: "label-tips" %>
        <%= f.select :country, @countries, { include_blank: true, selected:1 }, class: "form-control" %>

        <%= f.label :tips_type, "カテゴリー", class: "label-tips" %>
        <%= f.select :tips_type, @categories, { include_blank: true, selected: 1 }, class: "form-control" %>

        <%= f.label :tips_content, "内容", class: "label-tips" %>
        <%= f.text_field :tips_content, class: "form-control" %>

        <% if logged_in? %>
          <%= f.label :user_favorite, class: "checkbox inline checkbox-favorite", for: "user_favorite" do %>
            <%= f.check_box :user_favorite, id: "user_favorite" %>
            <span>お気に入りのみ表示する。</span>
          <% end %>
        <% end %>

        <%= f.submit "検索", class: "btn btn-tips-form" %>
      <% end %>
    </div>
    
    <%= will_paginate %>
      <div class="card-group">
        <% @tips.each do |tip| %>
          <div class="card center-block" style="width: 45rem;">
            <% if tip.street_view.present? %>
              <iframe src="<%= tip.street_view %>" class="card-iframe" width="600" height="450" style="border:0;"
                      allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            <% elsif tip.img.present? %>
              <%= image_tag tip.img.url, class: 'rounded-circle mr15', width: '100%' %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= tip.country + " " + tip.tips_type %></h5>
              <p class="card-text"><%= tip.tips_content %></p>
              <% if logged_in? %>
                <%= render 'favorite', tip: tip %>
                <%= link_to "Tips詳細", user_tip_path(@user, tip), class: "btn btn-primary btn-card" %>
                <% if (current_user?(@user) || current_user.admin?) %>
                  <%= link_to "Tips編集", edit_user_tip_path(@user, tip), class: "btn btn-success btn-card" %>
                <% end %>
              <% else %>
                <%= link_to "Tips詳細", user_tip_path(@user, tip), class: "btn btn-primary btn-card" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% will_paginate %>
  </div>
</div>

app/views/tips/new.html.erb
<% provide(:title, "新規投稿") %>

<h1>新規投稿</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_with(model: @user, url: user_tips_path, method: :post, local: true) do |f| %>
      <%= render 'shared/tip_error_messages' %>
      <%= f.fields_for :tips do |tip| %>
        <%= tip.label :country, "国名", class: "label-tips" %>
        <%= tip.select :country, @countries, { include_blank: true, selected: 1 }, class: "form-control" %>

        <%= tip.label :tips_type, "カテゴリー", class: "label-tips" %>
        <%= tip.select :tips_type, @categories, { include_blank: true, selected: 1 }, class: "form-control" %>

        <%= tip.label :tips_content, "内容", class: "label-tips" %>
        <%= tip.text_area :tips_content, class: "form-control" %>

        <%= tip.label :street_view, "ストリートビューURL", class: "label-tips" %>
        <%= link_to "URLの貼り付け方はこちら", tips_how_to_street_view_path, remote: true, class: "how-to" %>
        <%= tip.text_field :street_view, class: "form-control" %>

        <%= tip.label :img, "画像", class: "label-tips" %>
        <%= tip.file_field :img, class: 'form-control' %>
        <%= tip.hidden_field :img_cache %>

      <% end %>
      <%= f.submit "投稿", class: "btn btn-block btn-primary btn-tips-form" %>
    <% end %>
  </div>
</div>

<div id="how-to-street-view" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/tips/show.html.erb
<% provide(:title, @tip.country + " " + @tip.tips_type) %>

<h1><%= @tip.country + "　" + @tip.tips_type %></h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="center">
      <% if logged_in? %>
        <%= render 'favorite', tip: @tip %>
      <% end %>
      <h2>特徴</h2>
      <p><%= @tip.tips_content %></p>
      <br>
      <% if @tip.street_view.present? %>
        <iframe src="<%= @tip.street_view %>" width="100%" height="450" style="border:0;"
                      allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
      <% end %>

      <% if @tip.img.present? %>
        <p>
          <%= image_tag @tip.img.url, width: '100%' %>
        </p>
      <% end %>

      <% if logged_in? %>
        <% if (current_user?(@user) || current_user.admin?) %>
          <%= link_to "Tips編集", edit_user_tip_path(@user, @tip), class: "btn btn-success btn-tips-show" %>
          <%= link_to "削除", user_tip_path(@user, @tip), method: :delete,
                      data: { confirm: "このTipsを削除してよろしいですか？"},
                      class: "btn btn-danger btn-tips-show" %> 
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tips/tips_index.html.erb
<% provide(:title, "Tips") %>

<h1>Tips一覧</h1>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="index-form">
      <%= form_with(scope: :tips_condition, url: tips_index_path, method: :get, local: true) do |f| %>
        <%= f.label :country, "国名", class: "label-tips" %>
        <%= f.select :country, @countries, { include_blank: true, selected:1 }, class: "form-control" %>

        <%= f.label :tips_type, "カテゴリー", class: "label-tips" %>
        <%= f.select :tips_type, @categories, { include_blank: true, selected: 1 }, class: "form-control" %>

        <%= f.label :tips_content, "内容", class: "label-tips" %>
        <%= f.text_field :tips_content, class: "form-control" %>

        <% if logged_in? %>
          <%= f.label :user_favorite, class: "checkbox inline checkbox-favorite", for: "user_favorite" do %>
            <%= f.check_box :user_favorite, id: "user_favorite" %>
            <span>お気に入りのみ表示する。</span>
          <% end %>
        <% end %>

        <%= f.submit "検索", class: "btn btn-tips-form" %>
      <% end %>
    </div>
    
    <%= will_paginate %>
      <div class="card-group">
        <% @tips.each do |tip| %>
          <% user = User.find(tip.user_id) %>
          <%# カード表示 %>
          <div class="card center-block" style="width: 45rem;">
            <% if tip.street_view.present? %>
              <iframe src="<%= tip.street_view %>" class="card-iframe" width="600" height="450" style="border:0;"
                      allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            <% elsif tip.img.present? %>
              <%= image_tag tip.img.url, class: 'rounded-circle mr15', width: '100%' %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= tip.country + " " + tip.tips_type %></h5>
              <p class="card-text"><%= tip.tips_content %></p>
              <% if logged_in? %>
                <%= render 'favorite', tip: tip %>
                <%= link_to "Tips詳細", user_tip_path(user, tip), class: "btn btn-primary btn-card" %>
                <% if (current_user?(user) || current_user.admin?) %>
                  <%= link_to "Tips編集", edit_user_tip_path(user, tip), class: "btn btn-success btn-card" %>
                <% end %>
              <% else %>
                <%= link_to "Tips詳細", user_tip_path(user, tip), class: "btn btn-primary btn-card" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% will_paginate %>
  </div>
</div>