config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/callback', to: 'sessions#google_create'
  delete '/logout', to: 'sessions#destroy'
  post '/favorite/:id', to: 'favorites#create', as: 'create_favorite'
  delete '/favorite/:id', to: 'favorites#destroy', as: 'destroy_favorite'
  get 'tips_index', to: 'tips#tips_index'
  get 'tips/how_to_street_view'

  resources :users do
    resources :tips
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_google_login.html.erb
<% unless logged_in? %>
  <script src="https://accounts.google.com/gsi/client" async defer></script>
  <div id="g_id_onload"
    data-client_id="80642622284-6kqq3sqv2usj1v152msmhqg1vn5kc1bb.apps.googleusercontent.com"
    data-login_uri="https://geowiki.fly.dev/callback"
    data-auto_prompt="false">
  </div>
  <div class="g_id_signin"
    data-type="standard"
    data-size="large"
    data-theme="outline"
    data-text="signup_with"
    data-shape="rectangular"
    data-logo_alignment="left">
  </div>
  <br>
  <p>または</p>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-tips" >
  <div class="container">
    <%= link_to "GeoWiki", root_path, class: "header-string", id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Tips一覧", tips_index_path, class: "header-string" %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "ユーザー一覧", users_path, class: "header-string" %></li>
          <% end %>
          <li><%= link_to "Tips投稿", new_user_tip_path(current_user), class: "header-string" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle header-string" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "アカウント修正", edit_user_path(current_user) %></li>
              <li><%= link_to "投稿したTips", user_tips_path(current_user) %></li>
              <li><%= link_to "お気に入りTips", tips_index_path(tips_condition: {user_favorite: "1"}) %></li>
              <li class="divider"></li>
              <li><%= link_to "ログアウト", logout_path, method: :delete, class: "header-string" %></li>
            </ul>
          </li>
          <li><%= link_to "ログアウト", logout_path, method: :delete, class: "header-string" %></li>
        <% else %>
          <li><%= link_to "アカウント作成", new_user_path, class: "header-string" %></li>
          <li><%= link_to "ログイン", login_path, class: "header-string" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= create_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>